repos:
  - repo: local
    hooks:
      - id: update-tracker
        name: "Update Tracker"
        entry: "./update_tracker.py"
        language: python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
